### ISSUE TITLE
NoMethodError: undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#134]
https://sentry.io/nossas-cidades/rebu-api-server/issues/200433557/

```
NoMethodError: undefined method `gsub' for nil:NilClass
  app/services/donation_service.rb:149:in `phone'
    phone_number = number.gsub(/\D/, ' ').split(' ')
  app/services/donation_service.rb:135:in `customer_params'
    ddd: self.phone(donation.activist.phone)[:ddd],
  app/services/donation_service.rb:65:in `block in create_transaction'
    @transaction.customer = self.customer_params(donation, address)
  app/services/donation_service.rb:63:in `create_transaction'
    ActiveRecord::Base.transaction do
  app/services/donation_service.rb:14:in `run'
    self.create_transaction(donation, address)
...
(93 additional frame(s) were not displayed)

NoMethodError: undefined method `gsub' for nil:NilClass
```

**Comment by luizalbsilva** [comment]
Please review if production has the last version, this problem has been corrected a week ago.
