### ISSUE TITLE
NoMethodError: undefined method `copy_to_string' for #<ActivistAction::ActiveRecord_AssociationRelation:0x007f22...

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#193]
https://sentry.io/nossas-cidades/bonde-server/issues/231828796/

```
NoMethodError: undefined method `copy_to_string' for #<ActivistAction::ActiveRecord_AssociationRelation:0x007f2208929240>
  app/controllers/communities/activist_actions_controller.rb:15:in `block (2 levels) in index'
    send_data collection.copy_to_string, type: Mime::CSV, disposition: "attachment; filename=activist_actions_#{DateTime.now.to_i}_#{community.name.parameterize}.csv"
  app/controllers/communities/activist_actions_controller.rb:10:in `index'
    respond_with do |format|
...
(92 additional frame(s) were not displayed)

NoMethodError: undefined method `copy_to_string' for #<ActivistAction::ActiveRecord_AssociationRelation:0x007f2208929240>
```

**Comment by devton** [comment]
fixed on https://github.com/nossas/bonde-server/pull/194 this error is because are missing the config for use copy command on this model
