### ISSUE TITLE
PagarMe::ResponseError: Timed out connecting to server

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#282]
https://sentry.io/nossas-cidades/bonde-server/issues/279624561/

```
Net::OpenTimeout: execution expired
  app/services/donation_service.rb:89:in `find_or_create_card'
    if card.create
  app/services/donation_service.rb:18:in `new_transaction'
    self.find_or_create_card(donation) unless donation.boleto?
  app/services/donation_service.rb:39:in `block in create_transaction'
    @transaction = self.new_transaction(donation)
  app/services/donation_service.rb:38:in `create_transaction'
    ActiveRecord::Base.transaction do
  app/services/donation_service.rb:14:in `run'
    self.create_transaction(donation, address)
...
(106 additional frame(s) were not displayed)

RestClient::Exceptions::OpenTimeout: Timed out connecting to server
  app/services/donation_service.rb:89:in `find_or_create_card'
    if card.create
  app/services/donation_service.rb:18:in `new_transaction'
    self.find_or_create_card(donation) unless donation.boleto?
  app/services/donation_service.rb:39:in `block in create_transaction'
    @transaction = self.new_transaction(donation)
  app/services/donation_service.rb:38:in `create_transaction'
    ActiveRecord::Base.transaction do
  app/services/donation_service.rb:14:in `run'
    self.create_transaction(donation, address)
...
(100 additional frame(s) were not displayed)

JSON::ParserError: JSON::ParserError
  app/services/donation_service.rb:89:in `find_or_create_card'
    if card.create
  app/services/donation_service.rb:18:in `new_transaction'
    self.find_or_create_card(donation) unless donation.boleto?
  app/services/donation_service.rb:39:in `block in create_transaction'
    @transaction = self.new_transaction(donation)
  app/services/donation_service.rb:38:in `create_transaction'
    ActiveRecord::Base.transaction do
  app/services/donation_service.rb:14:in `run'
    self.create_transaction(donation, address)
...
(99 additional frame(s) were not displayed)

MultiJson::ParseError: JSON::ParserError
PagarMe::ResponseError: Timed out connecting to server
  app/services/donation_service.rb:89:in `find_or_create_card'
    if card.create
  app/services/donation_service.rb:18:in `new_transaction'
    self.find_or_create_card(donation) unless donation.boleto?
  app/services/donation_service.rb:39:in `block in create_transaction'
    @transaction = self.new_transaction(donation)
  app/services/donation_service.rb:38:in `create_transaction'
    ActiveRecord::Base.transaction do
  app/services/donation_service.rb:14:in `run'
    self.create_transaction(donation, address)
...
(98 additional frame(s) were not displayed)

PagarMe::ResponseError: Timed out connecting to server
```

**Comment by lpirola** [comment]
Add more info about payload received to have more info about failed action.
