### ISSUE TITLE
PagarMe::ValidationError: Número do cartão está faltando, Nome do portador do cartão está faltando, Data de expiração do ca...

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#307]
https://sentry.io/nossas-cidades/bonde-server/issues/287766321/

```
RestClient::BadRequest: 400 Bad Request
  app/models/subscription.rb:96:in `charge_next_payment'
    transaction.charge
  app/workers/subscription_worker.rb:11:in `perform'
    subscription.charge_next_payment
...
(37 additional frame(s) were not displayed)

PagarMe::ValidationError: Número do cartão está faltando, Nome do portador do cartão está faltando, Data de expiração do cartão está faltando, Código de segurança do cartão está faltando
  app/models/subscription.rb:96:in `charge_next_payment'
    transaction.charge
  app/workers/subscription_worker.rb:11:in `perform'
    subscription.charge_next_payment
...
(30 additional frame(s) were not displayed)

Número do cartão está faltando, Nome do portador do cartão está faltando, Data de expiração do cartão está faltando, Código de segurança do cartão está faltando
```

**Comment by lpirola** [comment]
PR #306
