### ISSUE TITLE
Error with seed rake command

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-server#349]
```
➜  bonde-client git:(feature-upgrade-webpack) ✗ docker-compose exec api-v1 rake db:seed
I, [2017-08-01T22:44:36.693623 #26]  INFO -- : Raven 2.4.0 configured not to capture errors: DSN not set
D, [2017-08-01T22:44:37.848167 #26] DEBUG -- :   ActiveRecord::SchemaMigration Load (5.6ms)  SELECT "schema_migrations".* FROM "schema_migrations"
D, [2017-08-01T22:44:37.911610 #26] DEBUG -- :   User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "foo@bar.com"]]
D, [2017-08-01T22:44:38.091305 #26] DEBUG -- :    (0.3ms)  BEGIN
D, [2017-08-01T22:44:38.118161 #26] DEBUG -- :   SQL (16.2ms)  INSERT INTO "users" ("email", "uid", "provider", "encrypted_password", "first_name", "last_name", "admin", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["email", "foo@bar.com"], ["uid", "foo@bar.com"], ["provider", "email"], ["encrypted_password", "$2a$11$Fqq53zHGfKf4/XSGs3Fs/.vrnNwzEurkskYY7GGinnlCk0n1Jsxkm"], ["first_name", "Foo"], ["last_name", "Bar"], ["admin", "f"], ["created_at", "2017-08-02 01:44:38.099043"], ["updated_at", "2017-08-02 01:44:38.099043"]]
D, [2017-08-01T22:44:38.128985 #26] DEBUG -- :    (8.6ms)  COMMIT
D, [2017-08-01T22:44:38.134079 #26] DEBUG -- :   User Load (1.5ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "admin_foo@bar.com"]]
D, [2017-08-01T22:44:38.291866 #26] DEBUG -- : undefined method `skip_confirmation!' for #<User:0x00561ab1ecbea0> excluded from capture: DSN not set
rake aborted!
NoMethodError: undefined method `skip_confirmation!' for #<User:0x00561ab1ecbea0>
/usr/app/db/seeds.rb:26:in `block in <top (required)>'
/usr/app/db/seeds.rb:19:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Comment by lpirola** [comment]
https://github.com/nossas/bonde-server/commit/849b47000f8611c430723d1e00a08e548ff00a38
